# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00571152bdb9c28dcebede281e02d103b1b8dc2f9c9b4eec4a84e90e0d22e9542363ac25ccc96c7db82467aef0f202ad9f97a4b8eca3a64f9e5ae3b74a5c78b0

test:
  secret_key_base: 06afd05fd1154b8e53fe642d1e9fd5d8fc7a6fedf03e906d044497c641e3fa4ef8184c5cb5d93f8bce51d10fe29d66e332cc78ccd60b94bf899f9d22c04d2559

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
